title: AI Debate Project
description: Exploring complex topics through AI-simulated debates
baseurl: "/debateai"
url: "https://alain1405.github.io"
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Build settings
exclude:
  - .github/
  - venv/
  - .venv/
  - debates/
  - poetry.lock
  - pyproject.toml
  - README.md
  - main.py

# Default front matter for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "AI Debate System"