name: Daily Debate Generation

on:
  schedule:
    - cron: '0 12 * * *'  # Run daily at 12:00 UTC
  workflow_dispatch:       # Allow manual triggers for testing

jobs:
  generate-debate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper git operations
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 'latest'
          
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
          
      - uses: actions/cache@v3
        name: Cache Poetry dependencies
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
          
      - name: Install dependencies
        run: poetry install --no-root
          
      - name: Generate new debate
        run: |
          mkdir -p debates _posts
          poetry run python main.py --non-interactive --default-format "Mediated Dialogue" --iterations 50
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'Alain'
          git config --global user.email 'alain1405@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git add debates/ _posts/
          git diff --quiet && git diff --staged --quiet || git commit -m "Add debate for $(date +%Y-%m-%d)"
          git push
      
      # Build and deploy to GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
      
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
